global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - "/etc/prometheus/alert-rules.yml"

scrape_configs:
  # Collect native /metrics from task-manager-api
  - job_name: 'task-manager-api'
    metrics_path: /metrics
    static_configs:
      - targets: ['task-manager-api:3002']

  # External health check via Blackbox Exporter
  - job_name: 'api_health_check'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - http://task-manager-api:3002/api/status
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115
